# -*- coding: utf-8 -*-
"""calculate_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7aBQ9i6ypFKReR4Hk-e4ij8FcRki36D
"""

import pandas as pd

def calculate_metrics(actual_value, predicted_value):
    """
    Calculates Loss, Accuracy, Recall, Precision, F1-Score, and Confusion Matrix
    using pandas only (no sklearn).

    Parameters:
        actual_value (list or array): Ground truth labels (0 or 1)
        predicted_value (list or array): Predicted labels (0 or 1)

    Returns:
        dict: {
            'Loss': float,
            'Accuracy': float,
            'Recall': float,
            'Precision': float,
            'F1-Score': float,
            'Confusion Matrix': {'TP': int, 'FP': int, 'TN': int, 'FN': int}
        }
    """
    # Build a DataFrame to work with pandas easily
    df = pd.DataFrame({
        'actual': actual_value,
        'predicted': predicted_value
    })

    # Confusion matrix components
    TP = int(((df['actual'] == 1) & (df['predicted'] == 1)).sum())
    TN = int(((df['actual'] == 0) & (df['predicted'] == 0)).sum())
    FP = int(((df['actual'] == 0) & (df['predicted'] == 1)).sum())
    FN = int(((df['actual'] == 1) & (df['predicted'] == 0)).sum())

    total = TP + TN + FP + FN

    # Accuracy
    accuracy = (TP + TN) / total if total > 0 else 0

    # Loss (0/1 misclassification loss)
    loss = (FP + FN) / total if total > 0 else 0

    # Precision
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0

    # Recall
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0

    # F1-Score
    f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return {
        'Loss': round(loss, 4),
        'Accuracy': round(accuracy, 4),
        'Recall': round(recall, 4),
        'Precision': round(precision, 4),
        'F1-Score': round(f1_score, 4),
        'Confusion Matrix': {
            'TP': TP,
            'FP': FP,
            'TN': TN,
            'FN': FN
        }
    }

# Example usage / quick test
if __name__ == "__main__":
    actual = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
    predicted = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]

    result = calculate_metrics(actual, predicted)
    print(result)